server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
        secure: false # cámbialo a true cuando uses HTTPS
        same-site: strict

spring:
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update # crea/actualiza tablas automáticamente
    show-sql: true # muestra SQL en consola
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console # consola accesible en http://localhost:8080/h2-console

jwt:
  secret: "MDEyMzQ1Njc4OUFCQ0RFRjAxMjM0NTY3ODlBQkNERUYwMTIzNDU2Nzg5QUJDREVGMDEyMzQ1Njc4OQ=="
  expiration-ms: 3600000

logging:
  level:
    org.springframework.security: DEBUG
